modified main.rb and added a new file methods
Sick-Carlito/tic-tac-toe pull request #2
Opened 2019-11-04 14:34 UTC by Sick-Carlito

2019-11-05 12:41 UTC, stratospherique requested changes
### Impressive work Team :clap: However, I have some notes that you need to address in order to get approval for this milestone. check :arrow_down: 

- **[REQUIRED]** The project is collaborative. Why I can only see @Sick-Carlito pushed commits? :pray:  it's mandatory to explain.

- **[REQUIRED]** Add more info to Readme.md and make it more descriptive.

- I added some code comments below. Take a look at them and refactor your code.

### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

_Happy coding_ :v: 
**Ahmed Mahfoudh**

2019-11-05 12:41 UTC, stratospherique commented on bin/main.rb
> +    @game = Game.new
- `Game` here is supposedly the **Methods** class that you have in the `lib` folder

2019-11-05 12:41 UTC, stratospherique commented on bin/main.rb
> +    display_board
- Displaying the board twice might be unpleasant from a UX perspective.

2019-11-05 14:44 UTC, Sick-Carlito commented on bin/main.rb
> +    @game = Game.new
My partner wasn't around for a while but he's back now. You will be able to see his commits soon enough.

2019-11-06 07:31 UTC, AdnanAfsari approved these changes
**Status : Approved**

Hello @Sick-Carlito @cochabambinoski ✋ 

You made all the changes reviewer requested. so its a 👍 from me.

Happy Coding
Adnan Afsari

2019-11-06 14:07 UTC, Sick-Carlito commented
Thanks guys!!

2019-11-06 14:30 UTC, merged